export default {
  INIT_CONNECTION: 'INIT_CONNECTION',
  INIT_CONNECTION_STORE: 'INIT_CONNECTION_STORE',
  WS_RESPONSE: 'WS_RESPONSE',

  CHANGE_MODAL_WINDOW_STATE: 'CHANGE_MODAL_WINDOW_STATE',
  CHANGE_MODAL_WINDOW_STATE_STORE: 'CHANGE_MODAL_WINDOW_STATE_STORE',

  CHANGE_BALANCE: 'CHANGE_BALANCE',
  CHANGE_BALANCE_STORE: 'CHANGE_BALANCE_STORE',

  CHANGE_VIEW_NEWS: 'CHANGE_VIEW_NEWS',
  CHANGE_VIEW_RACE: 'CHANGE_VIEW_RACE',
  CHANGE_VIEW_QUOTES: 'CHANGE_VIEW_QUOTES',

  RATES_HISTORY: 'RATES_HISTORY',
  RATES_HISTORY_STORE: 'RATES_HISTORY_STORE',

  RATES_UPDATE: 'RATES_UPDATE',
  RATES_UPDATE_STORE: 'RATES_UPDATE_STORE',

  CHANGE_THEME: 'CHANGE_THEME',
  CHANGE_THEME_STORE: 'CHANGE_THEME_STORE',

  // FILTER_INSTRUMENTS: 'FILTER_INSTRUMENTS',
  // FILTER_INSTRUMENTS_STORE: 'FILTER_INSTRUMENTS_STORE',

  FILTER_INSTRUMENTS: 'FILTER_INSTRUMENTS',
  FILTER_MARKET_FIELD: 'FILTER_MARKET_FIELD',

  INSTRUMENT_ISFREEZE: 'INSTRUMENT_ISFREEZE',
  INSTRUMENT_ISFREEZE_STORE: 'INSTRUMENT_ISFREEZE_STORE',
  
  GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_ERROR: 'GET_POSTS_ERROR',
  SET_SELECTED_POST_ID: 'SET_SELECTED_POST_ID',
  DEFAULT_COUNT_POSTS: 10,

}