export default {
  INIT_CONNECTION: 'INIT_CONNECTION',
  INIT_CONNECTION_STORE: 'INIT_CONNECTION_STORE',

  CHANGE_MODAL_WINDOW_STATE: 'CHANGE_MODAL_WINDOW_STATE',
  CHANGE_MODAL_WINDOW_STATE_STORE: 'CHANGE_MODAL_WINDOW_STATE_STORE',

  CHANGE_BALANCE: 'CHANGE_BALANCE',
  CHANGE_BALANCE_STORE: 'CHANGE_BALANCE_STORE',

  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  TOGGLE_CHAT_MODULE: 'TOGGLE_CHAT_MODULE',
  CHANGE_STATE_SELECTED_USER: 'CHANGE_STATE_SELECTED_USER',

  CHANGE_THEME: 'CHANGE_THEME',
  CHANGE_THEME_STORE: 'CHANGE_THEME_STORE',

  CHANGE_VIEW_NEWS: 'CHANGE_VIEW_NEWS',
  CHANGE_VIEW_RACE: 'CHANGE_VIEW_RACE',
  CHANGE_VIEW_QUOTES: 'CHANGE_VIEW_QUOTES',

  GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_ERROR: 'GET_POSTS_ERROR',
  SET_SELECTED_POST_ID: 'SET_SELECTED_POST_ID',
  DEFAULT_COUNT_POSTS: 10,

  TOGGLE_MODAL: 'TOGGLE_MODAL',
}
