export default {
    INIT_CONNECTION: 'INIT_CONNECTION',
    INIT_CONNECTION_STORE: 'INIT_CONNECTION_STORE',

    CHANGE_MODAL_WINDOW_STATE: 'CHANGE_MODAL_WINDOW_STATE',
    CHANGE_MODAL_WINDOW_STATE_STORE: 'CHANGE_MODAL_WINDOW_STATE_STORE',

    CHANGE_BALANCE: 'CHANGE_BALANCE',
    CHANGE_BALANCE_STORE: 'CHANGE_BALANCE_STORE',

    CHANGE_VIEW_NEWS: 'CHANGE_VIEW_NEWS',
    CHANGE_VIEW_RACE: 'CHANGE_VIEW_RACE',
    CHANGE_VIEW_QUOTES: 'CHANGE_VIEW_QUOTES',
}